#!/bin/bash

set -x
FOLDER_NAME=$1

if [[ -n $FOLDER_NAME ]]; then
    $CURRENT_PATH=$RANDOM
fi

RUN_NUMBER=0
mkdir -p $HOME/DOE/$FOLDER_NAME

./launch_bellerophon --popSize=600 --error=0.15 --pmut=0.5 --output=/home/seclab/DOE/$FOLDER_NAME/prova_$RUN_NUMBER.txt 
./launch_bellerophon --popSize=800 --error=0.15 --pmut=0.5 --output=/home/seclab/DOE/$FOLDER_NAME/prova_$RUN_NUMBER.txt 
./launch_bellerophon --popSize=1000 --error=0.15 --pmut=0.5 --output=/home/seclab/DOE/$FOLDER_NAME/prova_$RUN_NUMBER.txt 
./launch_bellerophon --popSize=1500 --error=0.15 --pmut=0.5 --output=/home/seclab/DOE/$FOLDER_NAME/prova_$RUN_NUMBER.txt 

./launch_bellerophon --popSize=600 --error=0.15 --pmut=0.6 --output=/home/seclab/DOE/$FOLDER_NAME/prova_$RUN_NUMBER.txt 
./launch_bellerophon --popSize=800 --error=0.15 --pmut=0.6 --output=/home/seclab/DOE/$FOLDER_NAME/prova_$RUN_NUMBER.txt 
./launch_bellerophon --popSize=1000 --error=0.15 --pmut=0.6 --output=/home/seclab/DOE/$FOLDER_NAME/prova_$RUN_NUMBER.txt 
./launch_bellerophon --popSize=1500 --error=0.15 --pmut=0.6 --output=/home/seclab/DOE/$FOLDER_NAME/prova_$RUN_NUMBER.txt

./launch_bellerophon --popSize=600 --error=0.15 --pmut=0.7 --output=/home/seclab/DOE/$FOLDER_NAME/prova_$RUN_NUMBER.txt 
./launch_bellerophon --popSize=800 --error=0.15 --pmut=0.7 --output=/home/seclab/DOE/$FOLDER_NAME/prova_$RUN_NUMBER.txt 
./launch_bellerophon --popSize=1000 --error=0.15 --pmut=0.7 --output=/home/seclab/DOE/$FOLDER_NAME/prova_$RUN_NUMBER.txt 
./launch_bellerophon --popSize=1500 --error=0.15 --pmut=0.7 --output=/home/seclab/DOE/$FOLDER_NAME/prova_$RUN_NUMBER.txt

./launch_bellerophon --popSize=600 --error=0.15 --pmut=0.8 --output=/home/seclab/DOE/$FOLDER_NAME/prova_$RUN_NUMBER.txt 
./launch_bellerophon --popSize=800 --error=0.15 --pmut=0.8 --output=/home/seclab/DOE/$FOLDER_NAME/prova_$RUN_NUMBER.txt 
./launch_bellerophon --popSize=1000 --error=0.15 --pmut=0.8 --output=/home/seclab/DOE/$FOLDER_NAME/prova_$RUN_NUMBER.txt 
./launch_bellerophon --popSize=1500 --error=0.15 --pmut=0.8 --output=/home/seclab/DOE/$FOLDER_NAME/prova_$RUN_NUMBER.txt

./launch_bellerophon --popSize=600 --error=0.15 --pmut=0.9 --output=/home/seclab/DOE/$FOLDER_NAME/prova_$RUN_NUMBER.txt 
./launch_bellerophon --popSize=800 --error=0.15 --pmut=0.9 --output=/home/seclab/DOE/$FOLDER_NAME/prova_$RUN_NUMBER.txt 
./launch_bellerophon --popSize=1000 --error=0.15 --pmut=0.9 --output=/home/seclab/DOE/$FOLDER_NAME/prova_$RUN_NUMBER.txt 
./launch_bellerophon --popSize=1500 --error=0.15 --pmut=0.9 --output=/home/seclab/DOE/$FOLDER_NAME/prova_$RUN_NUMBER.txt

cd $HOME/DOE
tar -zcvf bellero_$FOLDER_NAME.tar.gz $FOLDER_NAME
echo "Lo script di Bellerofonte è terminato." | mail -s "Bellerofonte" "andrea.aletto8@gmail.com" -A bellero_$FOLDER_NAME.zip